
      window.onload = function () {
        // Begin Swagger UI call region
        const ui = SwaggerUIBundle({
          spec: {
            openapi: "3.0.1",
            info: { title: "Common", description: "", version: "1.0.0" },
            tags: [{ name: "CMS" }, { name: "User" }],
            paths: {
              "/v2/admin/user(1297)": {
                patch: {
                  summary: "修改用户手机号",
                  "x-apifox-folder": "CMS",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["CMS"],
                  parameters: [
                    {
                      name: "Prefer",
                      in: "header",
                      description: "",
                      required: true,
                      example: "return=representation",
                      schema: { type: "string" },
                    },
                    {
                      name: "Authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJmYTlmOWVjMGU3YTgxMWVjYTQ4MTAyNDJhYzExMDAwOCIsImV4cCI6MTcwNDk1NzUyMywianRpIjoiOGRjN2MzODEtZGU5Zi00Y2JlLTlmZjEtYWRkMWY2OWFmNWRiIiwiaWF0IjoxNzA0MzUyNzIzLCJ1aWQiOiIxNjMiLCJzaWQiOiI2ZWYyM2VmMTY4Mjc0ZjBmYWE3MWM1Mjc0YmYyYWY5MSJ9.qVvNCp20FyJZnnjYMao2Sxa0t6DkheVT5n_QU0hMUOM",
                      schema: { type: "string" },
                    },
                    {
                      name: "Content-Type",
                      in: "header",
                      description: "",
                      required: true,
                      example: "application/json",
                      schema: { type: "string" },
                    },
                    {
                      name: "X-Request-Id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "6cee0470d6f0",
                      schema: { type: "string" },
                    },
                  ],
                  requestBody: {
                    content: {
                      "application/json": {
                        schema: {
                          type: "object",
                          properties: {
                            name: { type: "string" },
                            phone_number: { type: "string" },
                            description: { type: "string" },
                            phone_code: { type: "string" },
                            is_teacher: { type: "boolean" },
                          },
                          required: [
                            "name",
                            "phone_number",
                            "description",
                            "phone_code",
                            "is_teacher",
                          ],
                          "x-apifox-ignore-properties": [],
                          "x-apifox-orders": [
                            "name",
                            "phone_number",
                            "description",
                            "phone_code",
                            "is_teacher",
                          ],
                        },
                        example: {
                          name: "user1957",
                          phone_number: "15402301081",
                          description: "test test test",
                          phone_code: "86",
                          is_teacher: false,
                        },
                      },
                    },
                  },
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {},
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": [],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140076157-run",
                },
              },
              "/v2/user/info/game": {
                patch: {
                  summary: "LOL清空game info",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIzNmE4NmNjNWE1NGExMWVlOWYxNDAyNDJhYzExMDAwNSIsImV4cCI6MTcwNDc4MDQ3NywianRpIjoiNDhkOTBhMTEtNDQzNi00NDUxLWE3ZTQtN2EwNDg5ODlkYjE4IiwiaWF0IjoxNzA0Nzc5NTc3LCJ1aWQiOiIxMjgyIiwic2lkIjoiYjIxMGYwNjY3MTk0NDFmMDk4MjFiZjU0ZTk2Nzc5ZGMifQ.u220hiMM4Y2I5Z3ABxxvZZIg6Ux1-bj-dLklQifzFfg",
                      schema: { type: "string" },
                    },
                    {
                      name: "content-type",
                      in: "header",
                      description: "",
                      required: true,
                      example: "application/json",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "951460bfcf49",
                      schema: { type: "string" },
                    },
                  ],
                  requestBody: {
                    content: {
                      "application/json": {
                        schema: {
                          type: "array",
                          items: {
                            type: "object",
                            properties: { game_info_id: { type: "integer" } },
                            required: ["game_info_id"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["game_info_id"],
                          },
                        },
                        example: [
                          { game_info_id: 1 },
                          { game_info_id: 2 },
                          { game_info_id: 3 },
                          { game_info_id: 4 },
                          { game_info_id: 5 },
                          { game_info_id: 12 },
                          { game_info_id: 13 },
                          { game_info_id: 15 },
                          { game_info_id: 21 },
                          { game_info_id: 39 },
                          { game_info_id: 40 },
                          { game_info_id: 41 },
                          { game_info_id: 42 },
                          { game_info_id: 43 },
                          { game_info_id: 44 },
                          { game_info_id: 45 },
                        ],
                      },
                    },
                  },
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {},
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": [],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140105676-run",
                },
              },
              "/v2/admin/UserTokenAction/Adjust": {
                post: {
                  summary: "调整token接口（数量以及过期日期）",
                  "x-apifox-folder": "CMS",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["CMS"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJmYTlmOWVjMGU3YTgxMWVjYTQ4MTAyNDJhYzExMDAwOCIsImV4cCI6MTcwNDk1NzUyMywianRpIjoiOGRjN2MzODEtZGU5Zi00Y2JlLTlmZjEtYWRkMWY2OWFmNWRiIiwiaWF0IjoxNzA0MzUyNzIzLCJ1aWQiOiIxNjMiLCJzaWQiOiI2ZWYyM2VmMTY4Mjc0ZjBmYWE3MWM1Mjc0YmYyYWY5MSJ9.qVvNCp20FyJZnnjYMao2Sxa0t6DkheVT5n_QU0hMUOM",
                      schema: { type: "string" },
                    },
                    {
                      name: "content-type",
                      in: "header",
                      description: "",
                      required: true,
                      example: "application/json",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "2f35b58a3e8f",
                      schema: { type: "string" },
                    },
                  ],
                  requestBody: {
                    content: {
                      "application/json": {
                        schema: {
                          type: "object",
                          properties: {
                            is_refund: { type: "boolean" },
                            expire_date: { type: "string" },
                            user_id: { type: "integer", description: "用户id" },
                            amount: { type: "integer" },
                            note: { type: "string" },
                          },
                          required: [
                            "is_refund",
                            "expire_date",
                            "user_id",
                            "amount",
                            "note",
                          ],
                          "x-apifox-orders": [
                            "is_refund",
                            "expire_date",
                            "user_id",
                            "amount",
                            "note",
                          ],
                          "x-apifox-ignore-properties": [],
                        },
                        example: {
                          is_refund: false,
                          expire_date: "2024-01-10T06:20:11.326Z",
                          user_id: 1297,
                          amount: 1,
                          note: "调整token 数量日期",
                        },
                      },
                    },
                  },
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {},
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": [],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140125903-run",
                },
              },
              "/v2/user/login": {
                post: {
                  summary: "用户密码登录",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "developing",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "Authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example: "Bearer",
                      schema: { type: "string" },
                    },
                    {
                      name: "Content-Type",
                      in: "header",
                      description: "",
                      required: true,
                      example: "application/json",
                      schema: { type: "string" },
                    },
                    {
                      name: "X-Request-Id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "478086d7699e",
                      schema: { type: "string" },
                    },
                  ],
                  requestBody: {
                    content: {
                      "application/json": {
                        schema: {
                          type: "object",
                          properties: {
                            password: {
                              type: "string",
                              description: "sha256 encode",
                            },
                            phone_code: { type: "string" },
                            phone_number: { type: "string" },
                          },
                          required: ["password", "phone_code", "phone_number"],
                          "x-apifox-orders": [
                            "password",
                            "phone_code",
                            "phone_number",
                          ],
                          "x-apifox-ignore-properties": [],
                        },
                        example: {
                          password:
                            "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                          phone_code: "86",
                          phone_number: "15202304260",
                        },
                      },
                    },
                  },
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {
                              data: {
                                type: "object",
                                properties: {
                                  access_token: { type: "string" },
                                },
                                required: ["access_token"],
                                "x-apifox-ignore-properties": [],
                                "x-apifox-orders": ["access_token"],
                              },
                            },
                            required: ["data"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["data"],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140240048-run",
                },
              },
              "/v2/user/info": {
                get: {
                  summary: "获取用户信息",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIwMmQ3MTk0OGUzZDkxMWVkOWY4NjAyNDJhYzExMDAwZiIsImV4cCI6MTcwNTM5NjExOCwianRpIjoiY2UyNDRhODQtNjU4MS00N2Q0LWI5ODktNmMxNjI2MTcwZDU0IiwiaWF0IjoxNzA0NzkxMzE4LCJ1aWQiOiI5NzUiLCJzaWQiOiI1ZjMyN2VmOTllMGM0ZjIxYjEwYTMxMGIxZjczODU3YiJ9.ccoPNPNleAdZFlpjgB_TABFbmmNUfjFJawNvgnub7oE",
                      schema: { type: "string" },
                    },
                    {
                      name: "pragma",
                      in: "header",
                      description: "",
                      required: true,
                      example: "no-cache",
                      schema: { type: "string" },
                    },
                    {
                      name: "sentry-trace",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "58149ebf5c8740bd9dd148246dfae4b6-8f33cf417714551e-1",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "8f53a01b850d",
                      schema: { type: "string" },
                    },
                  ],
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {
                              data: {
                                type: "object",
                                properties: {
                                  id: { type: "integer" },
                                  avatar_url: { type: "string" },
                                  discord_id: { type: "string" },
                                  email: { type: "string" },
                                  is_assistant: { type: "boolean" },
                                  is_teacher: { type: "boolean" },
                                  is_trial: { type: "boolean" },
                                  marketing_info: { type: "null" },
                                  name: { type: "string" },
                                  phone_code: { type: "string" },
                                  phone_number: { type: "string" },
                                  status: { type: "string" },
                                  uuid: { type: "string" },
                                  wechat_id: { type: "null" },
                                  gender: { type: "string" },
                                  date_of_birth: { type: "string" },
                                  city: { type: "string" },
                                  district: { type: "string" },
                                  address: { type: "string" },
                                  token_balance: { type: "integer" },
                                  token_expire_date: { type: "string" },
                                  is_default_avatar_url: { type: "boolean" },
                                  lead_info: {
                                    type: "object",
                                    properties: {
                                      stage_code: { type: "string" },
                                      game_category_id: { type: "integer" },
                                      consultant_info: {
                                        type: "object",
                                        properties: {
                                          id: { type: "integer" },
                                          name: { type: "string" },
                                          qr_code_url: { type: "string" },
                                          wechat_id: { type: "string" },
                                        },
                                        required: [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                        "x-apifox-ignore-properties": [],
                                        "x-apifox-orders": [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                      },
                                    },
                                    required: [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                    "x-apifox-ignore-properties": [],
                                    "x-apifox-orders": [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                  },
                                },
                                required: [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                                "x-apifox-ignore-properties": [],
                                "x-apifox-orders": [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                              },
                            },
                            required: ["data"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["data"],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140241738-run",
                },
              },
              "/v2/User/token/balance": {
                get: {
                  summary: "获取用户token数量以及过期日期",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIwMmQ3MTk0OGUzZDkxMWVkOWY4NjAyNDJhYzExMDAwZiIsImV4cCI6MTcwNTM5NjExOCwianRpIjoiY2UyNDRhODQtNjU4MS00N2Q0LWI5ODktNmMxNjI2MTcwZDU0IiwiaWF0IjoxNzA0NzkxMzE4LCJ1aWQiOiI5NzUiLCJzaWQiOiI1ZjMyN2VmOTllMGM0ZjIxYjEwYTMxMGIxZjczODU3YiJ9.ccoPNPNleAdZFlpjgB_TABFbmmNUfjFJawNvgnub7oE",
                      schema: { type: "string" },
                    },
                    {
                      name: "pragma",
                      in: "header",
                      description: "",
                      required: true,
                      example: "no-cache",
                      schema: { type: "string" },
                    },
                    {
                      name: "sentry-trace",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "e362215eb981498a991c883f9e1a23c7-8269de3fa57f1394-1",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "b51a707a90df",
                      schema: { type: "string" },
                    },
                  ],
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {
                              data: {
                                type: "object",
                                properties: {
                                  token_balance: { type: "integer" },
                                  expire_date: { type: "string" },
                                },
                                required: ["token_balance", "expire_date"],
                                "x-apifox-ignore-properties": [],
                                "x-apifox-orders": [
                                  "token_balance",
                                  "expire_date",
                                ],
                              },
                            },
                            required: ["data"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["data"],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140242610-run",
                },
              },
              "/v2/Product/zh_CN/all": {
                get: {
                  summary: "获取产品信息（非token）",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIwMmQ3MTk0OGUzZDkxMWVkOWY4NjAyNDJhYzExMDAwZiIsImV4cCI6MTcwNTM5NjExOCwianRpIjoiY2UyNDRhODQtNjU4MS00N2Q0LWI5ODktNmMxNjI2MTcwZDU0IiwiaWF0IjoxNzA0NzkxMzE4LCJ1aWQiOiI5NzUiLCJzaWQiOiI1ZjMyN2VmOTllMGM0ZjIxYjEwYTMxMGIxZjczODU3YiJ9.ccoPNPNleAdZFlpjgB_TABFbmmNUfjFJawNvgnub7oE",
                      schema: { type: "string" },
                    },
                    {
                      name: "pragma",
                      in: "header",
                      description: "",
                      required: true,
                      example: "no-cache",
                      schema: { type: "string" },
                    },
                    {
                      name: "sentry-trace",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "58149ebf5c8740bd9dd148246dfae4b6-8f33cf417714551e-1",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "8f53a01b850d",
                      schema: { type: "string" },
                    },
                  ],
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {
                              data: {
                                type: "object",
                                properties: {
                                  id: { type: "integer" },
                                  avatar_url: { type: "string" },
                                  discord_id: { type: "string" },
                                  email: { type: "string" },
                                  is_assistant: { type: "boolean" },
                                  is_teacher: { type: "boolean" },
                                  is_trial: { type: "boolean" },
                                  marketing_info: { type: "null" },
                                  name: { type: "string" },
                                  phone_code: { type: "string" },
                                  phone_number: { type: "string" },
                                  status: { type: "string" },
                                  uuid: { type: "string" },
                                  wechat_id: { type: "null" },
                                  gender: { type: "string" },
                                  date_of_birth: { type: "string" },
                                  city: { type: "string" },
                                  district: { type: "string" },
                                  address: { type: "string" },
                                  token_balance: { type: "integer" },
                                  token_expire_date: { type: "string" },
                                  is_default_avatar_url: { type: "boolean" },
                                  lead_info: {
                                    type: "object",
                                    properties: {
                                      stage_code: { type: "string" },
                                      game_category_id: { type: "integer" },
                                      consultant_info: {
                                        type: "object",
                                        properties: {
                                          id: { type: "integer" },
                                          name: { type: "string" },
                                          qr_code_url: { type: "string" },
                                          wechat_id: { type: "string" },
                                        },
                                        required: [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                        "x-apifox-ignore-properties": [],
                                        "x-apifox-orders": [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                      },
                                    },
                                    required: [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                    "x-apifox-ignore-properties": [],
                                    "x-apifox-orders": [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                  },
                                },
                                required: [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                                "x-apifox-ignore-properties": [],
                                "x-apifox-orders": [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                              },
                            },
                            required: ["data"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["data"],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140243549-run",
                },
              },
              "/v2/Product/zh_CN/token": {
                get: {
                  summary: "获取产品信息token",
                  "x-apifox-folder": "User",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["User"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIwMmQ3MTk0OGUzZDkxMWVkOWY4NjAyNDJhYzExMDAwZiIsImV4cCI6MTcwNTM5NjExOCwianRpIjoiY2UyNDRhODQtNjU4MS00N2Q0LWI5ODktNmMxNjI2MTcwZDU0IiwiaWF0IjoxNzA0NzkxMzE4LCJ1aWQiOiI5NzUiLCJzaWQiOiI1ZjMyN2VmOTllMGM0ZjIxYjEwYTMxMGIxZjczODU3YiJ9.ccoPNPNleAdZFlpjgB_TABFbmmNUfjFJawNvgnub7oE",
                      schema: { type: "string" },
                    },
                    {
                      name: "pragma",
                      in: "header",
                      description: "",
                      required: true,
                      example: "no-cache",
                      schema: { type: "string" },
                    },
                    {
                      name: "sentry-trace",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "58149ebf5c8740bd9dd148246dfae4b6-8f33cf417714551e-1",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "8f53a01b850d",
                      schema: { type: "string" },
                    },
                  ],
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {
                              data: {
                                type: "object",
                                properties: {
                                  id: { type: "integer" },
                                  avatar_url: { type: "string" },
                                  discord_id: { type: "string" },
                                  email: { type: "string" },
                                  is_assistant: { type: "boolean" },
                                  is_teacher: { type: "boolean" },
                                  is_trial: { type: "boolean" },
                                  marketing_info: { type: "null" },
                                  name: { type: "string" },
                                  phone_code: { type: "string" },
                                  phone_number: { type: "string" },
                                  status: { type: "string" },
                                  uuid: { type: "string" },
                                  wechat_id: { type: "null" },
                                  gender: { type: "string" },
                                  date_of_birth: { type: "string" },
                                  city: { type: "string" },
                                  district: { type: "string" },
                                  address: { type: "string" },
                                  token_balance: { type: "integer" },
                                  token_expire_date: { type: "string" },
                                  is_default_avatar_url: { type: "boolean" },
                                  lead_info: {
                                    type: "object",
                                    properties: {
                                      stage_code: { type: "string" },
                                      game_category_id: { type: "integer" },
                                      consultant_info: {
                                        type: "object",
                                        properties: {
                                          id: { type: "integer" },
                                          name: { type: "string" },
                                          qr_code_url: { type: "string" },
                                          wechat_id: { type: "string" },
                                        },
                                        required: [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                        "x-apifox-ignore-properties": [],
                                        "x-apifox-orders": [
                                          "id",
                                          "name",
                                          "qr_code_url",
                                          "wechat_id",
                                        ],
                                      },
                                    },
                                    required: [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                    "x-apifox-ignore-properties": [],
                                    "x-apifox-orders": [
                                      "stage_code",
                                      "game_category_id",
                                      "consultant_info",
                                    ],
                                  },
                                },
                                required: [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                                "x-apifox-ignore-properties": [],
                                "x-apifox-orders": [
                                  "id",
                                  "avatar_url",
                                  "discord_id",
                                  "email",
                                  "is_assistant",
                                  "is_teacher",
                                  "is_trial",
                                  "marketing_info",
                                  "name",
                                  "phone_code",
                                  "phone_number",
                                  "status",
                                  "uuid",
                                  "wechat_id",
                                  "gender",
                                  "date_of_birth",
                                  "city",
                                  "district",
                                  "address",
                                  "token_balance",
                                  "token_expire_date",
                                  "is_default_avatar_url",
                                  "lead_info",
                                ],
                              },
                            },
                            required: ["data"],
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": ["data"],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140244055-run",
                },
              },
              "/v2/admin/Calendar/event": {
                post: {
                  summary: "创建calendar event ",
                  "x-apifox-folder": "CMS",
                  "x-apifox-status": "released",
                  deprecated: false,
                  description: "",
                  tags: ["CMS"],
                  parameters: [
                    {
                      name: "authority",
                      in: "header",
                      description: "",
                      required: true,
                      example: "api-test.gengesports.cn",
                      schema: { type: "string" },
                    },
                    {
                      name: "authorization",
                      in: "header",
                      description: "",
                      required: true,
                      example:
                        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJmYTlmOWVjMGU3YTgxMWVjYTQ4MTAyNDJhYzExMDAwOCIsImV4cCI6MTcwNDk1NzUyMywianRpIjoiOGRjN2MzODEtZGU5Zi00Y2JlLTlmZjEtYWRkMWY2OWFmNWRiIiwiaWF0IjoxNzA0MzUyNzIzLCJ1aWQiOiIxNjMiLCJzaWQiOiI2ZWYyM2VmMTY4Mjc0ZjBmYWE3MWM1Mjc0YmYyYWY5MSJ9.qVvNCp20FyJZnnjYMao2Sxa0t6DkheVT5n_QU0hMUOM",
                      schema: { type: "string" },
                    },
                    {
                      name: "content-type",
                      in: "header",
                      description: "",
                      required: true,
                      example: "application/json",
                      schema: { type: "string" },
                    },
                    {
                      name: "pragma",
                      in: "header",
                      description: "",
                      required: true,
                      example: "no-cache",
                      schema: { type: "string" },
                    },
                    {
                      name: "x-request-id",
                      in: "header",
                      description: "",
                      required: true,
                      example: "81c1516a4e56",
                      schema: { type: "string" },
                    },
                  ],
                  requestBody: {
                    content: {
                      "application/json": {
                        schema: {
                          type: "object",
                          properties: {
                            name: { type: "string" },
                            description: { type: "string" },
                            frequency: { type: "string" },
                            localization_id: { type: "integer" },
                            event_join_type: { type: "string" },
                            game_category_id: { type: "integer" },
                            coach_user_id: { type: "integer" },
                            calendar_location_id: { type: "integer" },
                            link: { type: "string" },
                            token_cost: { type: "integer" },
                            introduction: { type: "string" },
                            notice: { type: "string" },
                            user_role_count_restriction: {
                              type: "object",
                              properties: {},
                              "x-apifox-orders": [],
                              "x-apifox-ignore-properties": [],
                            },
                            banners: { type: "string" },
                            class_limit: { type: "string" },
                            max_enroll_count: { type: "integer" },
                            event_start_time: {
                              type: "string",
                              description: "修改开始时间",
                            },
                            event_end_time: {
                              type: "string",
                              description: "修改结束时间",
                            },
                            user_role_addition: {
                              type: "object",
                              properties: {
                                user_role_list: {
                                  type: "array",
                                  items: { type: "string" },
                                },
                              },
                              required: ["user_role_list"],
                              "x-apifox-orders": ["user_role_list"],
                              "x-apifox-ignore-properties": [],
                            },
                          },
                          required: [
                            "name",
                            "description",
                            "frequency",
                            "localization_id",
                            "event_join_type",
                            "game_category_id",
                            "coach_user_id",
                            "calendar_location_id",
                            "link",
                            "token_cost",
                            "introduction",
                            "notice",
                            "user_role_count_restriction",
                            "banners",
                            "class_limit",
                            "max_enroll_count",
                            "event_start_time",
                            "event_end_time",
                            "user_role_addition",
                          ],
                          "x-apifox-orders": [
                            "name",
                            "description",
                            "frequency",
                            "localization_id",
                            "event_join_type",
                            "game_category_id",
                            "coach_user_id",
                            "calendar_location_id",
                            "link",
                            "token_cost",
                            "introduction",
                            "notice",
                            "user_role_count_restriction",
                            "banners",
                            "class_limit",
                            "max_enroll_count",
                            "event_start_time",
                            "event_end_time",
                            "user_role_addition",
                          ],
                          "x-apifox-ignore-properties": [],
                        },
                        example: {
                          name: "create new one evevent",
                          description: "create new one evevent",
                          frequency: "Once",
                          localization_id: 2,
                          event_join_type: "Enroll",
                          game_category_id: 2,
                          coach_user_id: 163,
                          calendar_location_id: 2,
                          link: "# dfgsfdg",
                          token_cost: 1,
                          introduction: "test test",
                          notice: "test test",
                          user_role_count_restriction: {},
                          banners:
                            "https://gga-data-test.oss-accelerate.aliyuncs.com/upload-images/8eefe41c76934a8b93518ebbe0a3e310.gif",
                          class_limit: "",
                          max_enroll_count: 1,
                          event_start_time: "2024-01-08T16:00:00.000Z",
                          event_end_time: "2024-01-08T20:00:00.000Z",
                          user_role_addition: { user_role_list: [] },
                        },
                      },
                    },
                  },
                  responses: {
                    200: {
                      description: "成功",
                      content: {
                        "application/json": {
                          schema: {
                            type: "object",
                            properties: {},
                            "x-apifox-ignore-properties": [],
                            "x-apifox-orders": [],
                          },
                        },
                      },
                    },
                  },
                  "x-run-in-apifox":
                    "https://www.apifox.cn/web/project/3877458/apis/api-140246675-run",
                },
              },
            },
            components: { schemas: {} },
          },
          dom_id: "#swagger-ui",
          deepLinking: true,
          presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
          plugins: [SwaggerUIBundle.plugins.DownloadUrl],
          layout: "StandaloneLayout",
        });
        // End Swagger UI call region

        window.ui = ui;
      };
